fix(workflows): fix reusable build artifacts action and test

diff --git a/.github/workflows/reusable_build-artifacts.yaml b/.github/workflows/reusable_build-artifacts.yaml
--- a/.github/workflows/reusable_build-artifacts.yaml
+++ b/.github/workflows/reusable_build-artifacts.yaml
@@ -5,8 +5,14 @@ on:
     inputs:
       build-script:
         description: Path to the build script to execute
-        required: true
+        required: false
         type: string
+        default: ""
+      build-script-path:
+        description: Path to the build script to execute
+        required: false
+        type: string
+        default: ""
       artifact-directory:
         description: Directory that will contain all artifacts from this build
         required: true
@@ -42,9 +48,18 @@ jobs:
           if [ "${{ inputs.dry-run }}" = "true" ]; then
             dry_run_arg="--dry-run"
           fi
+          build_script_arg=""
+          if [ "${{ inputs.build-script }}" != "" ]; then
+            build_script_arg="--build-script ${inputs.build-script}"
+          elif [ "${{ inputs.build-script-path }}" != "" ]; then
+            build_script_arg="--build-script-path ${inputs.build-script-path}"
+          else
+            echo "Error: Either ${{ inputs.build-script }} or ${{ inputs.build-script-path }} must be provided"
+            exit 1
+          fi
           ${{ github.workspace }}/.github/workflows/build-artifacts/entrypoint.sh \
-            "${{ inputs.build-script }}" \
-            "${{ inputs.artifact-directory }}" \
+            $build_script_arg \
+            --artifact-directory "${{ inputs.artifact-directory }}" \
             $dry_run_arg
 
       - name: Upload Artifacts
